FROM golang:1.23
LABEL maintainer="OuterCyrex"

WORKDIR /workspace
COPY . /workspace

ENV GO111MODULE=auto
ENV GOPROXY=https://goproxy.cn,direct

RUN go mod tidy
RUN go build -o ./bin/GoGateway

CMD ["./bin/GoGateway", "--endpoint=proxy-server"]