services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile-ProxyServer
    ports:
      - "80:80"
      - "443:443"
      - "8801-8999:8801-8999"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./conf/config.yaml:/workspace/conf/config.yaml
    networks:
      - net

  dash-board:
    build:
      context: .
      dockerfile: Dockerfile-Dashboard
    ports:
      - "9710:9710"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./conf/config.yaml:/workspace/conf/config.yaml
    networks:
      - net

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./go_gateway.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      retries: 5
    networks:
      - net

networks:
  net:
    driver: bridge