// Code generated by hertz generator.

package main

import (
	"GoGateway/biz/middleware"
	"GoGateway/conf"
	"GoGateway/dao"
	"GoGateway/pkg"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"os"
)

func main() {
	hlog.SetLevel(hlog.LevelDebug)
	hlog.SetOutput(os.Stdout)

	dao.InitDB(dao.DefaultDSN())

	addr := fmt.Sprintf("%s:%d", conf.GetConfig().Host, conf.GetConfig().Port)

	h := server.Default(server.WithHostPorts(addr))

	h.Use(pkg.GetCors())
	h.Use(middleware.AccessLog())

	register(h)
	h.Spin()
}
