// Code generated by hertz generator.

package dashboard

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpaneldataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getflowstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdashservicestatMw() []app.HandlerFunc {
	// your code...
	return nil
}
