// Code generated by hertz generator.

package application

import (
	applicationDAO "GoGateway/dao/application"
	"GoGateway/pkg/status"
	applicationSVC "GoGateway/svc/application"
	"context"
	"errors"
	"gorm.io/gorm"
	"net/http"
	"time"

	application "GoGateway/biz/model/application"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ApplicationAddHTTP .
// @router /application/add/http [POST]
func ApplicationAddHTTP(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppAddHttpRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, status.NewErrorResponse(err.Error()))
		return
	}

	svc := applicationSVC.ApplicationSvcLayer{}
	if err := svc.NewApp(req); err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	resp := new(application.MessageResponse)

	resp.Message = "新建应用成功"

	c.JSON(consts.StatusOK, resp)
}

// ApplicationDetail .
// @router /application/detail/:id [GET]
func ApplicationDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	repo := applicationDAO.ApplicationRepository{}
	resp, err := repo.Find(&applicationDAO.Application{Model: gorm.Model{ID: uint(req.ID)}})

	if errors.Is(err, gorm.ErrRecordNotFound) {
		c.JSON(http.StatusNotFound, status.NewErrorResponse("应用信息不存在"))
	} else if err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp.ToHttpResponse())
}

// AppUpdate .
// @router /application/update/:id [PUT]
func AppUpdate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppUpdateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, status.NewErrorResponse(err.Error()))
		return
	}

	svc := applicationSVC.ApplicationSvcLayer{}
	if err := svc.UpdateApp(req); err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	resp := new(application.MessageResponse)

	resp.Message = "应用更新成功"

	c.JSON(consts.StatusOK, resp)
}

// AppDelete .
// @router /application/delete/:id [DELETE]
func AppDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppDeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, status.NewErrorResponse(err.Error()))
		return
	}

	svc := applicationSVC.ApplicationSvcLayer{}
	if err := svc.DeleteApp(req); err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	resp := new(application.MessageResponse)

	resp.Message = "应用删除成功"

	c.JSON(consts.StatusOK, resp)
}

// AppList .
// @router /application/list [GET]
func AppList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, status.NewErrorResponse(err.Error()))
		return
	}

	svc := applicationSVC.ApplicationSvcLayer{}
	respList, err := svc.AppList(req)
	if err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	c.JSON(consts.StatusOK, respList)
}

// AppStatic .
// @router /application/static/:id [GET]
func AppStatic(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.AppStatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, status.NewErrorResponse(err.Error()))
		return
	}

	var today []int64
	var yesterday []int64

	for i := 0; i <= time.Now().Hour(); i++ {
		today = append(today, 0)
	}

	for i := 0; i <= 23; i++ {
		yesterday = append(yesterday, 0)
	}

	c.JSON(consts.StatusOK, application.AppStatResponse{
		Today:     today,
		Yesterday: yesterday,
	})
}
