// Code generated by hertz generator.

package dashboard

import (
	"GoGateway/dao"
	applicationDAO "GoGateway/dao/application"
	serviceDAO "GoGateway/dao/services"
	"GoGateway/pkg/status"
	redisCounter "GoGateway/proxy/redis_counter"
	dashboardSVC "GoGateway/svc/dashboard"
	"context"
	"time"

	dashboard "GoGateway/biz/model/dashboard"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetPanelData .
// @router /dashboard/panel [GET]
func GetPanelData(ctx context.Context, c *app.RequestContext) {

	var serviceNum int64
	var appNum int64

	dao.DB.Model(&serviceDAO.ServiceInfo{}).Count(&serviceNum)
	dao.DB.Model(&applicationDAO.Application{}).Count(&appNum)

	total, qps := redisCounter.ServiceFlowCountHandler.GetAllInfo()

	c.JSON(consts.StatusOK, dashboard.PanelDataResponse{
		ServiceNum:      serviceNum,
		AppNum:          appNum,
		CurrentQps:      qps,
		TodayRequestNum: total,
	})
}

// GetFlowStatistics .
// @router /dashboard/stat [GET]
func GetFlowStatistics(ctx context.Context, c *app.RequestContext) {
	counter := redisCounter.RedisCounter{}

	yesterdayTime := time.Now().Add(time.Hour * 24 * -1)

	begin := time.Date(yesterdayTime.Year(), yesterdayTime.Month(), yesterdayTime.Day(), 0, 0, 0, 0, time.Local)

	var today []int64
	var yesterday []int64

	for i := 0; i <= 23; i++ {
		data, _ := counter.TotalHourCount(begin)
		yesterday = append(yesterday, data)
		begin = begin.Add(time.Hour * 1)
	}

	for i := 0; i <= time.Now().Hour(); i++ {
		data, _ := counter.TotalHourCount(begin)
		today = append(today, data)
		begin = begin.Add(time.Hour * 1)
	}

	resp := dashboard.FlowStatResponse{
		Today:     today,
		Yesterday: yesterday,
	}

	c.JSON(consts.StatusOK, resp)
}

// GetDashServiceStat .
// @router /dashboard/stat/service [GET]
func GetDashServiceStat(ctx context.Context, c *app.RequestContext) {

	svc := dashboardSVC.DashboardSvcLayer{}
	resp, err := svc.GetServiceStat()
	if err != nil {
		status.ErrToHttpResponse(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
