// Code generated by hertz generator.

package dashboard

import (
	"context"

	dashboard "GoGateway/biz/model/dashboard"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetPanelData .
// @router /dashboard/panel [GET]
func GetPanelData(ctx context.Context, c *app.RequestContext) {
	resp := new(dashboard.PanelDataResponse)

	c.JSON(consts.StatusOK, resp)
}
