// Code generated by hertz generator.

package application

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationaddhttpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _staticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appstaticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statMw() []app.HandlerFunc {
	// your code...
	return nil
}
