// Code generated by hertz generator.

package application

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationaddhttpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applicationdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
