// Code generated by hertz generator.

package services

import (
	"GoGateway/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicedeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceaddhttpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceupdatehttpMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.HotReloadMiddleware}
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _staticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicestaticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceaddgrpcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceaddtcpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _grpcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceupdategrpcMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.HotReloadMiddleware}
}

func _httpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tcpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceupdatetcpMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.HotReloadMiddleware}
}

func _statMw() []app.HandlerFunc {
	// your code...
	return nil
}
