// Code generated by hertz generator.

package services

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicedeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceaddhttpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}
