// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	admin "GoGateway/biz/router/admin"
	application "GoGateway/biz/router/application"
	services "GoGateway/biz/router/services"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	application.Register(r)

	services.Register(r)

	admin.Register(r)
}
